// packages/indobase-auth-ui/packages/svelte/src/lib/UI/Divider.svelte
<script lang="ts">
	import type { Appearance } from '$lib/types';
	import { css } from '@stitches/core';
	import { generateClassNames } from '@indobaseinc/auth-ui-shared';

	const dividerDefaultStyles = css({
		background: '$dividerBackground',
		display: 'block',
		margin: '16px 0',
		height: '1px',
		width: '100%'
	});

	type DivProps = svelte.JSX.HTMLAttributes<HTMLDivElement>;
	type $$Props = DivProps & {
		appearance?: Appearance;
	};

	export let appearance: Appearance = {};

	const classNames = generateClassNames('divider', dividerDefaultStyles(), appearance);
</script>

<div {...$$restProps} style={appearance?.style?.divider} class={classNames.join(' ')}>
	<slot />
</div>

// packages/indobase-auth-ui/packages/react/src/components/UI/Divider.tsx
import { css } from '@stitches/core'
import { generateClassNames } from '@indobaseinc/auth-ui-shared'
import { Appearance } from '../../types'

const dividerDefaultStyles = css({
  background: '$dividerBackground',
  display: 'block',
  margin: '16px 0',
  height: '1px',
  width: '100%',
})

interface DividerProps extends React.HTMLAttributes<HTMLDivElement> {
  appearance?: Appearance
}

const Divider: React.FC<DividerProps> = ({
  children,
  appearance,
  ...props
}) => {
  const classNames = generateClassNames(
    'divider',
    dividerDefaultStyles(),
    appearance
  )

  return (
    <div
      {...props}
      style={appearance?.style?.divider}
      className={classNames.join(' ')}
    ></div>
  )
}

export { Divider }
