// packages/indobase-auth-ui/packages/svelte/src/lib/UI/Label.svelte
<script lang="ts">
	import type { Appearance } from '$lib/types';
	import { css } from '@stitches/core';
	import { generateClassNames } from '@indobaseinc/auth-ui-shared';

	const labelDefaultStyles = css({
		fontFamily: '$labelFontFamily',
		fontSize: '$baseLabelSize',
		marginBottom: '$labelBottomMargin',
		color: '$inputLabelText',
		display: 'block'
	});

	type LabelProps = svelte.JSX.HTMLAttributes<HTMLLabelElement>;

	type $$Props = LabelProps & {
		appearance?: Appearance;
	};

	export let appearance: Appearance = {};

	$: classNames = generateClassNames('label', labelDefaultStyles(), appearance);
</script>

<label {...$$restProps} style={appearance?.style?.label} class={classNames.join(' ')}>
	<slot />
</label>

// packages/indobase-auth-ui/packages/react/src/components/UI/Label.tsx
import { css } from '@stitches/core'
import { generateClassNames } from '@indobaseinc/auth-ui-shared'
import { Appearance } from '../../types'

const labelDefaultStyles = css({
  fontFamily: '$labelFontFamily',
  fontSize: '$baseLabelSize',
  marginBottom: '$labelBottomMargin',
  color: '$inputLabelText',
  display: 'block',
})

interface LabelProps extends React.LabelHTMLAttributes<HTMLLabelElement> {
  children: React.ReactNode
  appearance?: Appearance
}

const Label: React.FC<LabelProps> = ({ children, appearance, ...props }) => {
  const classNames = generateClassNames(
    'label',
    labelDefaultStyles(),
    appearance
  )

  return (
    <label
      {...props}
      style={appearance?.style?.label}
      className={classNames.join(' ')}
    >
      {children}
    </label>
  )
}

export { Label }
