// packages/indobase-auth-ui/packages/svelte/src/lib/Auth/ui/SocialAuth.svelte
<script lang="ts">
	import type { Provider } from '@indobaseinc/auth-js';
	import type { IndobaseClient } from '@indobaseinc/indobase-js';
	import type {
		I18nVariables,
		ProviderScopes,
		SocialLayout,
		ViewType
	} from '@indobaseinc/auth-ui-shared';
	import type { Appearance } from '$lib/types';
	import Auth from '../Auth.svelte';

	export let supabaseClient: IndobaseClient;
	export let socialLayout: SocialLayout = 'vertical';
	export let providers: Provider[] = [];
	export let providerScopes: Partial<ProviderScopes> | undefined = undefined;
	export let queryParams: { [key: string]: string } | undefined = undefined;
	export let redirectTo: string | undefined = undefined;
	export let appearance: Appearance = {};
	export let theme: 'default' | string = 'default';
	export let localization: { variables?: I18nVariables } = {};
</script>

<Auth
	view="sign_in"
	showLinks={false}
	onlyThirdPartyProviders={true}
	{supabaseClient}
	{redirectTo}
	{socialLayout}
	{providers}
	{providerScopes}
	{queryParams}
	{appearance}
	{theme}
	{localization}
/>

// packages/indobase-auth-ui/packages/react/src/components/Auth/interfaces/SocialAuth.tsx
import type { Provider } from '@indobaseinc/auth-js'
import type { IndobaseClient } from '@indobaseinc/indobase-js'
import { useState } from 'react'
import {
  I18nVariables,
  ProviderScopes,
  SocialLayout,
  template,
} from '@indobaseinc/auth-ui-shared'
import { Appearance } from '../../../types'
import { Button, Container, Divider } from './../../UI/index.js'
import { Icons } from './../Icons.js'

interface SocialAuthProps {
  supabaseClient: IndobaseClient
  socialLayout?: SocialLayout
  providers?: Provider[]
  providerScopes?: Partial<ProviderScopes>
  queryParams?: { [key: string]: string }
  redirectTo?: RedirectTo
  onlyThirdPartyProviders?: boolean
  view?: 'sign_in' | 'sign_up' | 'magic_link'
  i18n?: I18nVariables
  appearance?: Appearance
}

type RedirectTo = undefined | string

function SocialAuth({
  supabaseClient,
  socialLayout = 'vertical',
  providers = ['github', 'google', 'azure'],
  providerScopes,
  queryParams,
  redirectTo,
  onlyThirdPartyProviders = true,
  view = 'sign_in',
  i18n,
  appearance,
}: SocialAuthProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const verticalSocialLayout = socialLayout === 'vertical' ? true : false

  const currentView = view === 'magic_link' ? 'sign_in' : view

  const handleProviderSignIn = async (provider: Provider) => {
    setLoading(true)
    const { error } = await supabaseClient.auth.signInWithOAuth({
      provider,
      options: {
        redirectTo,
        scopes: providerScopes?.[provider],
        queryParams,
      },
    })
    if (error) setError(error.message)
    setLoading(false)
  }

  function handleProviderNameEdgeCases(provider: string) {
    if (provider === 'linkedin_oidc') {
      return 'LinkedIn'
    }
    return provider
  }

  function capitalize(word: string) {
    const lower = word.toLowerCase()
    return word.charAt(0).toUpperCase() + lower.slice(1)
  }

  return (
    <>
      {providers && providers.length > 0 && (
        <>
          <Container gap="large" direction="vertical" appearance={appearance}>
            <Container
              direction={verticalSocialLayout ? 'vertical' : 'horizontal'}
              gap={verticalSocialLayout ? 'small' : 'medium'}
              appearance={appearance}
            >
              {providers.map((provider: Provider) => {
                return (
                  <Button
                    key={provider}
                    color="default"
                    loading={loading}
                    onClick={() => handleProviderSignIn(provider)}
                    appearance={appearance}
                  >
                    <Icons provider={provider} />
                    {verticalSocialLayout &&
                      template(
                        i18n?.[currentView]?.social_provider_text as string,
                        {
                          provider: capitalize(
                            handleProviderNameEdgeCases(provider)
                          ),
                        }
                      )}
                  </Button>
                )
              })}
            </Container>
          </Container>
          {!onlyThirdPartyProviders && <Divider appearance={appearance} />}
        </>
      )}
    </>
  )
}

export { SocialAuth }
