// packages/indobase-auth-ui/packages/react/src/components/UI/Message.tsx
import { css } from '@stitches/core'
import { generateClassNames } from '@indobaseinc/auth-ui-shared'
import { Appearance } from '../../types'

const messageDefaultStyles = css({
  fontFamily: '$bodyFontFamily',
  fontSize: '$baseInputSize',
  marginBottom: '$labelBottomMargin',
  display: 'block',
  textAlign: 'center',
  borderRadius: '0.375rem',
  padding: '1.5rem 1rem',
  lineHeight: '1rem',
  color: '$messageText',
  backgroundColor: '$messageBackground',
  border: '1px solid $messageBorder',
  variants: {
    color: {
      danger: {
        color: '$messageTextDanger',
        backgroundColor: '$messageBackgroundDanger',
        border: '1px solid $messageBorderDanger',
      },
    },
  },
})

interface MessageProps extends React.HTMLAttributes<HTMLSpanElement> {
  children: React.ReactNode
  color?: 'danger'
  appearance?: Appearance
}

const Message: React.FC<MessageProps> = ({
  children,
  appearance,
  ...props
}) => {
  const classNames = generateClassNames(
    'message',
    messageDefaultStyles({ color: props.color }),
    appearance
  )

  return (
    <span
      {...props}
      style={appearance?.style?.message}
      className={classNames.join(' ')}
    >
      {children}
    </span>
  )
}

export { Message }

// packages/indobase-auth-ui/packages/svelte/src/lib/UI/Message.svelte
<script lang="ts">
	import type { Appearance } from '$lib/types';
	import { css } from '@stitches/core';
	import { generateClassNames } from '@indobaseinc/auth-ui-shared';

	const messageDefaultStyles = css({
		fontFamily: '$bodyFontFamily',
		fontSize: '$baseInputSize',
		marginBottom: '$labelBottomMargin',
		display: 'block',
		textAlign: 'center',
		borderRadius: '0.375rem',
		padding: '1.5rem 1rem',
		lineHeight: '1rem',
		variants: {
			color: {
				default: {
					color: '$messageText',
					backgroundColor: '$messageBackground',
					border: '1px solid $messageBorder'
				},
				danger: {
					color: '$messageTextDanger',
					backgroundColor: '$messageBackgroundDanger',
					border: '1px solid $messageBorderDanger'
				}
			}
		}
	});

	type DivProps = svelte.JSX.HTMLAttributes<HTMLDivElement>;

	type $$Props = DivProps & {
		color?: 'default' | 'danger';
		appearance?: Appearance;
	};

	export let color: 'default' | 'danger' = 'default';
	export let appearance: Appearance = {};

	$: classNames = generateClassNames('message', messageDefaultStyles({ color }), appearance);
</script>

<span {...$$restProps} style={appearance?.style?.message} class={classNames.join(' ')}>
	<slot />
</span>
