// examples/user-management/react-user-management/src/App.jsx
import { useState, useEffect } from 'react'
import './App.css'
import { supabase } from './supabaseClient'
import Auth from './Auth'
import Account from './Account'

function App() {
  const [user, setUser] = useState(null)

  useEffect(() => {
    supabase.auth.getUser().then(({ data: { user } }) => {
      setUser(user)
    })

    supabase.auth.onAuthStateChange(async () => {
      const { data: { user } } = await supabase.auth.getUser()
      setUser(user)
    })
  }, [])

  return (
    <div className="container" style={{ padding: '50px 0 100px 0' }}>
      {!user ? <Auth /> : <Account key={user.id} user={user} />}
    </div>
  )
}

export default App

// examples/user-management/solid-user-management/src/App.tsx
import { Component, createEffect, createSignal } from 'solid-js'
import { supabase } from './supabaseClient'
import Account from './Account'
import Auth from './Auth'

const App: Component = () => {
	const [userId, setUserId] = createSignal<string | null>(null)
	const [userEmail, setUserEmail] = createSignal<string | null>(null)

	const syncClaims = async () => {
		const { data } = await supabase.auth.getClaims()
		setUserId((data?.claims.sub as string) ?? null)
		setUserEmail((data?.claims.email as string) ?? null)
	}

	createEffect(() => {
		syncClaims()

		supabase.auth.onAuthStateChange(() => {
			syncClaims()
		})
	})

	return (
		<div class="container" style={{ padding: '50px 0 100px 0' }}>
			{!userId() ? <Auth /> : <Account userId={userId()!} userEmail={userEmail()} />}
		</div>
	)
}

export default App
