// apps/studio/components/interfaces/ConnectSheet/content/solidjs/supabasejs/content.tsx
import { MultipleCodeBlock } from 'ui-patterns/MultipleCodeBlock'

import type { StepContentProps } from '@/components/interfaces/ConnectSheet/Connect.types'

const ContentFile = ({ projectKeys }: StepContentProps) => {
  const files = [
    {
      name: '.env.local',
      language: 'bash',
      code: [
        `VITE_INDOBASE_URL=${projectKeys.apiUrl ?? 'your-project-url'}`,
        projectKeys?.publishableKey
          ? `VITE_INDOBASE_PUBLISHABLE_DEFAULT_KEY=${projectKeys.publishableKey}`
          : `VITE_INDOBASE_ANON_KEY=${projectKeys.anonKey ?? 'your-anon-key'}`,
        '',
      ].join('\n'),
    },
    {
      name: 'utils/indobase.ts',
      language: 'ts',
      code: `
import { createClient } from "@indobaseinc/indobase-js";

const indobaseUrl = import.meta.env.VITE_INDOBASE_URL;
const indobaseKey = import.meta.env.${projectKeys.publishableKey ? 'VITE_INDOBASE_PUBLISHABLE_DEFAULT_KEY' : 'VITE_INDOBASE_ANON_KEY'};

export const indobase = createClient(indobaseUrl, indobaseKey);
`,
    },
    {
      name: 'src/App.tsx',
      language: 'tsx',
      code: `
import { indobase } from '../utils/indobase'
import { createResource, For } from "solid-js";

async function getTodos() {
  const { data: todos } = await indobase.from("todos").select();
  return todos;
}

function App() {
  const [todos] = createResource(getTodos);

  return (
    <ul>
      <For each={todos()}>{(todo) => <li>{todo.name}</li>}</For>
    </ul>
  );
}

export default App;
`,
    },
  ]

  return <MultipleCodeBlock files={files} />
}

export default ContentFile

// apps/studio/components/interfaces/ConnectSheet/content/nuxt/supabasejs/content.tsx
import { MultipleCodeBlock } from 'ui-patterns/MultipleCodeBlock'

import type { StepContentProps } from '@/components/interfaces/ConnectSheet/Connect.types'

const ContentFile = ({ projectKeys }: StepContentProps) => {
  const files = [
    {
      name: '.env.local',
      language: 'bash',
      code: [
        `INDOBASE_URL=${projectKeys.apiUrl ?? 'your-project-url'}`,
        `INDOBASE_KEY=${projectKeys.publishableKey ?? projectKeys.anonKey ?? 'your-anon-key'}`,
        '',
      ].join('\n'),
    },
    {
      name: 'nuxt.config.ts',
      language: 'ts',
      code: `
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      indobaseUrl: process.env.INDOBASE_URL,
      indobaseKey: process.env.INDOBASE_KEY,
    },
  },
})
`,
    },
    {
      name: 'app.vue',
      language: 'html',
      code: `
<script setup>
import { ref, onMounted } from 'vue'
import { createClient } from '@indobaseinc/indobase-js'

const config = useRuntimeConfig()
const indobase = createClient(config.public.indobaseUrl, config.public.indobaseKey)

const todos = ref([])

async function getTodos() {
  const { data } = await indobase.from('todos').select()
  todos.value = data
}

onMounted(() => {
  getTodos()
})
</script>

<template>
  <ul>
    <li v-for="todo in todos" :key="todo.id">{{ todo.name }}</li>
  </ul>
</template>
`,
    },
  ]

  return <MultipleCodeBlock files={files} />
}

export default ContentFile
