// packages/indobase-auth-ui/packages/react/src/components/Auth/interfaces/ForgottenPassword.tsx
import type { IndobaseClient } from '@indobaseinc/indobase-js'
import React, { useState } from 'react'
import { VIEWS, I18nVariables, RedirectTo } from '@indobaseinc/auth-ui-shared'
import { Appearance } from '../../../types'
import {
  Anchor,
  Button,
  Container,
  Input,
  Label,
  Message,
} from './../../UI/index.js'

function ForgottenPassword({
  setAuthView = () => {},
  supabaseClient,
  redirectTo,
  i18n,
  appearance,
  showLinks = false,
}: {
  setAuthView?: any
  supabaseClient: IndobaseClient
  redirectTo?: RedirectTo
  i18n?: I18nVariables
  appearance?: Appearance
  showLinks?: boolean
}) {
  const [email, setEmail] = useState('')
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const [loading, setLoading] = useState(false)

  const handlePasswordReset = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setError('')
    setMessage('')
    setLoading(true)
    const { error } = await supabaseClient.auth.resetPasswordForEmail(email, {
      redirectTo,
    })
    if (error) setError(error.message)
    else setMessage(i18n?.forgotten_password?.confirmation_text as string)
    setLoading(false)
  }

  const labels = i18n?.forgotten_password

  return (
    <form id="auth-forgot-password" onSubmit={handlePasswordReset}>
      <Container direction="vertical" gap="large" appearance={appearance}>
        <Container gap="large" direction="vertical" appearance={appearance}>
          <div>
            <Label htmlFor="email" appearance={appearance}>
              {labels?.email_label}
            </Label>
            <Input
              id="email"
              name="email"
              type="email"
              autoFocus
              placeholder={labels?.email_input_placeholder}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                setEmail(e.target.value)
              }
              appearance={appearance}
            />
          </div>
          <Button
            type="submit"
            color="primary"
            loading={loading}
            appearance={appearance}
          >
            {loading ? labels?.loading_button_label : labels?.button_label}
          </Button>
          {showLinks && (
            <Anchor
              href="#auth-sign-in"
              onClick={(e: React.MouseEvent<HTMLAnchorElement>) => {
                e.preventDefault()
                setAuthView(VIEWS.SIGN_IN)
              }}
              appearance={appearance}
            >
              {i18n?.sign_in?.link_text}
            </Anchor>
          )}
          {message && <Message appearance={appearance}>{message}</Message>}
          {error && (
            <Message color="danger" appearance={appearance}>
              {error}
            </Message>
          )}
        </Container>
      </Container>
    </form>
  )
}

export { ForgottenPassword }

// packages/indobase-auth-ui/packages/solid/src/components/Auth/interfaces/ForgottenPassword.tsx
import { SupabaseClient } from '@supabase/indobase-js'
import { createSignal, Setter } from 'solid-js'
import {
  I18nVariables,
  RedirectTo,
  ViewType,
  VIEWS,
} from '@supabase/auth-ui-shared'
import { Appearance, FormEvent } from '../../../types'
import { Anchor, Button, Container, Input, Label, Message } from '../../UI'

function ForgottenPassword(props: {
  setAuthView: Setter<ViewType>
  supabaseClient: SupabaseClient
  redirectTo?: RedirectTo
  i18n: I18nVariables
  appearance?: Appearance
  showLinks?: boolean
}) {
  const [email, setEmail] = createSignal('')
  const [error, setError] = createSignal('')
  const [message, setMessage] = createSignal('')
  const [loading, setLoading] = createSignal(false)

  const handlePasswordReset = async (e: FormEvent) => {
    e.preventDefault()
    setError('')
    setMessage('')
    setLoading(true)
    const { error } = await props.supabaseClient.auth.resetPasswordForEmail(
      email(),
      {
        redirectTo: props.redirectTo,
      }
    )
    if (error) setError(error.message)
    else setMessage(props.i18n.forgotten_password?.confirmation_text as string)
    setLoading(false)
  }

  return (
    <form id="auth-forgot-password" onSubmit={handlePasswordReset}>
      <Container gap="large" direction="vertical" appearance={props.appearance}>
        <Container
          gap="large"
          direction="vertical"
          appearance={props.appearance}
        >
          <div>
            <Label for="email" appearance={props.appearance}>
              {props.i18n?.forgotten_password?.email_label}
            </Label>
            <Input
              id="email"
              name="email"
              type="email"
              autofocus
              placeholder={
                props.i18n?.forgotten_password?.email_input_placeholder
              }
              onkeyup={(e) => setEmail(e.currentTarget.value)}
              appearance={props.appearance}
            />
          </div>
          <Button
            type="submit"
            color="primary"
            loading={loading()}
            appearance={props.appearance}
          >
            {props.i18n?.forgotten_password?.button_label}
          </Button>
        </Container>
        {props.showLinks && (
          <Anchor
            href="#auth-sign-in"
            onClick={(e) => {
              e.preventDefault()
              props.setAuthView(VIEWS.SIGN_IN)
            }}
            appearance={props.appearance}
          >
            {props.i18n?.sign_in?.link_text}
          </Anchor>
        )}
        {message && (
          <Message appearance={props.appearance}>{message()}</Message>
        )}
        {error && (
          <Message color="danger" appearance={props.appearance}>
            {error()}
          </Message>
        )}
      </Container>
    </form>
  )
}

export { ForgottenPassword }
